CREATE TABLE IF NOT EXISTS User (
id INTEGER NOT NULL,
nome VARCHAR(20),
cognome VARCHAR(20),
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS Phone(
id INTEGER NOT NULL,
numero VARCHAR(10),
user_id INTEGER,
PRIMARY KEY(id),
FOREIGN KEY(user_id)
);